version: "3"
services:
  api_wewiza:
    build: api-wewiza/.
    restart: always
    ports:
      - "8080:8080"
      - "587:587" # SMTP for email
    environment:
      - PORT=8080
    networks:
      - public-wewiza-network
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

networks:
  public-wewiza-network:
    external: true
